pipeline {
    agent {
        label 'slave && debian'
    }
    tools {
        maven 'Maven 3.3.9'
        jdk 'jdk8'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                archiveArtifacts artifacts: 'target/*.jar'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                sshPublisher(
                    continueOnError: false, 
                    failOnError: true,
                    publishers: [
                        sshPublisherDesc(
                            configName: "App Server",
                            verbose: true,
                            transfers: [
                                sshTransfer(execCommand: "/bin/rm -rf /opt/app/*"),
                                sshTransfer(sourceFiles: "target/*.jar", removePrefix: "target"),
                                sshTransfer(execCommand: "/usr/local/openjdk-8/bin/java -jar /opt/app/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App.main")
                            ]
                        )
                    ]
                )
            }
        }
    }
}
